/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/3d/scene.glb -o src/components/Maps.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/3d/scene.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['21jumpStreet_interaction_v1'].geometry} material={materials['21jumpStreet_interaction_v1']} position={[-1.95, 5.424, -6.083]} rotation={[Math.PI / 2, 0, 0]} scale={0.29} />
      <mesh geometry={nodes.backToFuture_interaction_v1.geometry} material={materials.backToFuture_interaction_v1} position={[-4.473, 1.861, -6.99]} rotation={[Math.PI / 2, 0, 0]} scale={0.29} />
      <mesh geometry={nodes.badBoys_interaction_v1.geometry} material={materials.badBoys_interaction_v1} position={[-3.747, 5.424, -6.083]} rotation={[Math.PI / 2, 0, 0]} scale={0.29} />
      <group position={[1.507, -2.958, 0.541]} rotation={[0, -1.571, 0]} scale={0.846}>
        <mesh geometry={nodes.Cube239.geometry} material={materials['Cement.005']} />
        <mesh geometry={nodes.Cube239_1.geometry} material={materials['Scratched Metal 2.010']} />
      </group>
      <group position={[1.507, -1.917, 0.541]} rotation={[0, -1.571, 0]} scale={0.846}>
        <mesh geometry={nodes.Cube240.geometry} material={materials['Cement.005']} />
        <mesh geometry={nodes.Cube240_1.geometry} material={materials['Scratched Metal 2.011']} />
      </group>
      <mesh geometry={nodes.Bevelling.geometry} material={materials['Cement.005']} position={[-11.578, -3.614, 0.541]} rotation={[0, -1.571, 0]} scale={0.846} />
      <mesh geometry={nodes.bladeRunner_interaction_v1.geometry} material={materials['blade runner']} position={[4.869, 1.838, -7.012]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.bohemianRhapsody_interaction_v1.geometry} material={materials.bohemianRhapsody_interaction_v1} position={[-0.135, 5.424, -6.083]} rotation={[Math.PI / 2, 0, 0]} scale={0.29} />
      <group position={[1.507, -2.958, 0.541]} rotation={[0, -1.571, 0]} scale={0.846}>
        <mesh geometry={nodes.Cube238.geometry} material={materials['Glide.010']} />
        <mesh geometry={nodes.Cube238_1.geometry} material={materials['Scratched Metal 2.011']} />
        <mesh geometry={nodes.Cube238_2.geometry} material={materials['Bumped Metal.006']} />
      </group>
      <mesh geometry={nodes.Bottom_layer003.geometry} material={materials['Scratched Metal 2.011']} position={[1.507, -3.043, 0.541]} rotation={[0, -1.571, 0]} scale={0.846} />
      <mesh geometry={nodes.Bottom_layer004.geometry} material={nodes.Bottom_layer004.material} position={[1.507, -2.958, 0.541]} rotation={[0, -1.571, 0]} scale={0.846} />
      <group position={[1.507, -2.958, 0.541]} rotation={[0, -1.571, 0]} scale={0.846}>
        <mesh geometry={nodes.Cube235.geometry} material={materials['Scratched Metal 2.011']} />
        <mesh geometry={nodes.Cube235_1.geometry} material={materials['Bumped Metal.006']} />
      </group>
      <mesh geometry={nodes.Bottom_layer006.geometry} material={materials['Scratched Metal 2.011']} position={[-5.662, 1.392, 6.083]} rotation={[Math.PI, 0, Math.PI]} scale={0.846} />
      <mesh geometry={nodes.Bottom_layer007.geometry} material={materials['Cement.005']} position={[1.507, -2.958, 0.541]} rotation={[0, -1.571, 0]} scale={0.846} />
      <mesh geometry={nodes.Circle007.geometry} material={materials['Scratched Metal 2.011']} position={[7.955, 0.496, 8.269]} rotation={[Math.PI / 2, 0, 0]} scale={0.144} />
      <mesh geometry={nodes.Circle008.geometry} material={materials['Scratched Metal 2.011']} position={[7.955, -0.225, 8.269]} rotation={[Math.PI / 2, 0, 0]} scale={0.144} />
      <mesh geometry={nodes.Circle009.geometry} material={materials['Scratched Metal 2.011']} position={[7.955, -0.922, 8.269]} rotation={[Math.PI / 2, 0, 0]} scale={0.144} />
      <mesh geometry={nodes.Circle010.geometry} material={materials['Scratched Metal 2.011']} position={[-6.23, 0.541, -5.905]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.144} />
      <mesh geometry={nodes.Circle011.geometry} material={materials['Scratched Metal 2.011']} position={[-6.23, -0.18, -5.905]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.144} />
      <mesh geometry={nodes.Circle012.geometry} material={materials['Scratched Metal 2.011']} position={[-6.23, -0.877, -5.905]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.144} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.017']} position={[-5.402, -0.013, 3.5]} rotation={[0, 1.571, 0]} />
      <group position={[8.311, 1.026, 1.513]} rotation={[Math.PI, 0, Math.PI]} scale={[-0.142, -0.017, -0.178]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['Material.029']} />
      </group>
      <group position={[8.221, 0.551, 1.438]} rotation={[Math.PI, 0, Math.PI]} scale={[-0.266, -0.04, -0.363]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials['Material.018']} />
      </group>
      <group position={[-0.066, -2.958, 7.093]} rotation={[0, -1.571, 0]} scale={0.846}>
        <mesh geometry={nodes.Cube214.geometry} material={materials['Cement.005']} />
        <mesh geometry={nodes.Cube214_1.geometry} material={materials['Scratched Metal 2.011']} />
      </group>
      <group position={[-3.692, -0.456, 5.787]} rotation={[0, -1.571, 0]} scale={[2.162, 0.383, 2.197]}>
        <mesh geometry={nodes.Cube209.geometry} material={materials['Cement.005']} />
        <mesh geometry={nodes.Cube209_1.geometry} material={materials['Scratched Metal 2.011']} />
      </group>
      <mesh geometry={nodes.Cube028.geometry} material={materials['Scratched Metal 2.011']} position={[-8.328, -3.759, 2.907]} rotation={[0, -1.571, 0]} scale={0.846} />
      <group position={[-5.084, -2.958, 1.871]} rotation={[Math.PI, 0, Math.PI]} scale={0.846}>
        <mesh geometry={nodes.Cube222.geometry} material={materials['Cement.005']} />
        <mesh geometry={nodes.Cube222_1.geometry} material={materials['Scratched Metal 2.011']} />
      </group>
      <mesh geometry={nodes.Cube032.geometry} material={materials['Bumped Metal.006']} position={[-5.567, 0.72, -2.999]} rotation={[0, -1.571, 0]} scale={[0.846, 1.082, 0.846]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials['Bumped Metal.006']} position={[-5.567, 1.614, -4.484]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.846, 1.55, 0.846]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials['Bumped Metal.006']} position={[-5.588, 0.72, 0.214]} rotation={[0, -1.571, 0]} scale={[0.846, 1.082, 0.846]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials['Bumped Metal.006']} position={[-5.588, 1.614, -1.275]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.846, 1.593, 0.846]} />
      <mesh geometry={nodes.Cube036.geometry} material={materials['Bumped Metal.006']} position={[-5.588, 0.72, 5.717]} rotation={[0, -1.571, 0]} scale={[0.846, 1.082, 0.846]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Bumped Metal.006']} position={[-5.588, 1.614, 4.022]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.846, 1.79, 0.846]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Bumped Metal.006']} position={[-3.89, 0.581, 7.603]} scale={[0.846, 1.156, 0.846]} />
      <mesh geometry={nodes.Cube039.geometry} material={materials['Bumped Metal.006']} position={[-5.336, 1.659, 7.603]} rotation={[0, 0, -Math.PI / 2]} scale={[0.846, 1.625, 0.846]} />
      <mesh geometry={nodes.Cube040.geometry} material={materials['Bumped Metal.006']} position={[3.185, 0.571, 7.603]} scale={[0.846, 1.141, 0.846]} />
      <mesh geometry={nodes.Cube041.geometry} material={materials['Bumped Metal.006']} position={[2.125, 1.638, 7.603]} rotation={[0, 0, -Math.PI / 2]} scale={[0.846, 1.138, 0.846]} />
      <mesh geometry={nodes.Cube042.geometry} material={materials['Bumped Metal.006']} position={[5.478, 0.571, 7.603]} scale={[0.846, 1.141, 0.846]} />
      <mesh geometry={nodes.Cube043.geometry} material={materials['Bumped Metal.006']} position={[4.497, 1.638, 7.603]} rotation={[0, 0, -Math.PI / 2]} scale={[0.846, 1.138, 0.846]} />
      <mesh geometry={nodes.Cube044.geometry} material={materials['Bumped Metal.006']} position={[-4.247, -2.967, 7.603]} scale={0.846} />
      <mesh geometry={nodes.Cube045.geometry} material={materials['Bumped Metal.006']} position={[-3.262, -2.967, 7.603]} scale={0.846} />
      <mesh geometry={nodes.Cube046.geometry} material={materials['Bumped Metal.006']} position={[-5.139, -1.584, 7.603]} rotation={[0, 0, -Math.PI / 2]} scale={0.846} />
      <mesh geometry={nodes.Cube047.geometry} material={materials['Bumped Metal.006']} position={[-5.509, -2.966, 5.194]} rotation={[0, -1.571, 0]} scale={0.846} />
      <mesh geometry={nodes.Cube048.geometry} material={materials['Bumped Metal.006']} position={[-5.509, -2.966, 6.178]} rotation={[0, -1.571, 0]} scale={0.846} />
      <mesh geometry={nodes.Cube049.geometry} material={materials['Bumped Metal.006']} position={[-5.509, -1.582, 3.952]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.846, 0.934, 0.846]} />
      <mesh geometry={nodes.Cube050.geometry} material={materials['Bumped Metal.006']} position={[3.225, -2.967, 7.603]} scale={0.846} />
      <mesh geometry={nodes.Cube051.geometry} material={materials['Bumped Metal.006']} position={[5.449, -2.967, 7.603]} scale={0.846} />
      <mesh geometry={nodes.Cube052.geometry} material={materials['Bumped Metal.006']} position={[2.119, -1.584, 7.603]} rotation={[0, 0, -Math.PI / 2]} scale={[0.846, 1.271, 0.846]} />
      <mesh geometry={nodes.Cube053.geometry} material={materials['Bumped Metal.006']} position={[-3.709, 6.394, 7.132]} scale={[0.846, 1.257, 0.846]} />
      <mesh geometry={nodes.Cube054.geometry} material={materials['Bumped Metal.006']} position={[-3.71, 8.671, 7.132]} rotation={[0, 0, -Math.PI / 2]} scale={[0.846, 1.328, 0.846]} />
      <mesh geometry={nodes.Cube055.geometry} material={materials['Bumped Metal.006']} position={[-3.576, 2.842, 7.132]} scale={[0.846, 1.257, 0.846]} />
      <mesh geometry={nodes.Cube056.geometry} material={materials['Bumped Metal.006']} position={[-4.958, 3.968, 7.132]} rotation={[0, 0, -Math.PI / 2]} scale={[0.846, 1.328, 0.846]} />
      <mesh geometry={nodes.Cube057.geometry} material={materials['Bumped Metal.006']} position={[3.587, 6.394, 7.132]} scale={[0.846, 1.257, 0.846]} />
      <mesh geometry={nodes.Cube058.geometry} material={materials['Bumped Metal.006']} position={[3.586, 8.671, 7.132]} rotation={[0, 0, -Math.PI / 2]} scale={[0.846, 1.328, 0.846]} />
      <mesh geometry={nodes.Cube059.geometry} material={materials['Bumped Metal.006']} position={[3.589, 2.842, 7.132]} scale={[0.846, 1.257, 0.846]} />
      <mesh geometry={nodes.Cube060.geometry} material={materials['Bumped Metal.006']} position={[2.338, 3.968, 7.132]} rotation={[0, 0, -Math.PI / 2]} scale={[0.846, 1.328, 0.846]} />
      <mesh geometry={nodes.Cube061.geometry} material={materials['Bumped Metal.006']} position={[6.457, 6.394, 7.132]} scale={[0.846, 1.257, 0.846]} />
      <mesh geometry={nodes.Cube062.geometry} material={materials['Bumped Metal.006']} position={[6.456, 8.671, 7.132]} rotation={[0, 0, -Math.PI / 2]} scale={[0.846, 1.328, 0.846]} />
      <mesh geometry={nodes.Cube065.geometry} material={materials['Bumped Metal.006']} position={[-5.088, 6.41, 5.654]} rotation={[0, -1.571, 0]} scale={[0.846, 1.257, 0.846]} />
      <mesh geometry={nodes.Cube066.geometry} material={materials['Bumped Metal.006']} position={[-5.088, 8.687, 5.653]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.846, 1.328, 0.846]} />
      <mesh geometry={nodes.Cube067.geometry} material={materials['Bumped Metal.006']} position={[-5.088, 2.858, 5.631]} rotation={[0, -1.571, 0]} scale={[0.846, 1.257, 0.846]} />
      <mesh geometry={nodes.Cube068.geometry} material={materials['Bumped Metal.006']} position={[-5.088, 3.984, 4.405]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.846, 1.328, 0.846]} />
      <mesh geometry={nodes.Cube069.geometry} material={materials['Bumped Metal.006']} position={[-5.088, 6.41, -1.753]} rotation={[0, -1.571, 0]} scale={[0.846, 1.257, 0.846]} />
      <mesh geometry={nodes.Cube070.geometry} material={materials['Bumped Metal.006']} position={[-5.088, 8.687, -1.754]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.846, 1.328, 0.846]} />
      <mesh geometry={nodes.Cube071.geometry} material={materials['Bumped Metal.006']} position={[-5.088, 2.858, -1.777]} rotation={[0, -1.571, 0]} scale={[0.846, 1.257, 0.846]} />
      <mesh geometry={nodes.Cube072.geometry} material={materials['Bumped Metal.006']} position={[-5.088, 3.984, -3.002]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.846, 1.328, 0.846]} />
      <mesh geometry={nodes.Cube073.geometry} material={materials['Bumped Metal.006']} position={[-5.088, 6.41, -4.478]} rotation={[0, -1.571, 0]} scale={[0.846, 1.257, 0.846]} />
      <mesh geometry={nodes.Cube074.geometry} material={materials['Bumped Metal.006']} position={[-5.088, 8.687, -4.479]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.846, 1.328, 0.846]} />
      <mesh geometry={nodes.Cube077.geometry} material={materials['Bumped Metal.006']} position={[-0.001, 5.524, 7.96]} />
      <mesh geometry={nodes.Cube078.geometry} material={materials['Bumped Metal.006']} position={[-1.191, 3.768, 7.957]} rotation={[0, 0, -Math.PI / 2]} scale={[0.846, 1.247, 0.846]} />
      <mesh geometry={nodes.Cube079.geometry} material={materials['Bumped Metal.006']} position={[-0.029, 5.828, 7.957]} rotation={[0, 0, -Math.PI / 2]} scale={[0.846, 1.205, 0.846]} />
      <group position={[1.495, -2.969, 8.537]} rotation={[0, -Math.PI / 2, 0]} scale={[0.184, 2.536, 0.184]}>
        <mesh geometry={nodes.Cube144.geometry} material={materials['Cement.005']} />
        <mesh geometry={nodes.Cube144_1.geometry} material={materials['Scratched Metal 2.011']} />
      </group>
      <mesh geometry={nodes.Cube096.geometry} material={materials['Scratched Metal 2.011']} position={[-5.549, -2.958, 5.64]} rotation={[0, -1.571, 0]} scale={0.846} />
      <mesh geometry={nodes.Cube097.geometry} material={materials['Scratched Metal 2.011']} position={[-3.73, -2.958, 7.588]} scale={0.846} />
      <mesh geometry={nodes.Cube098.geometry} material={materials['Scratched Metal 2.011']} position={[4.402, -2.958, 7.588]} scale={0.846} />
      <mesh geometry={nodes.Cube099.geometry} material={materials['Scratched Metal 2.010']} position={[1.507, 3.72, 0.541]} rotation={[0, -Math.PI / 2, 0]} scale={[6.877, 0.318, 6.877]} />
      <group position={[-1.623, -2.969, 8.516]} rotation={[0, -Math.PI / 2, 0]} scale={[0.184, 2.536, 0.184]}>
        <mesh geometry={nodes.Cube224.geometry} material={materials['Cement.005']} />
        <mesh geometry={nodes.Cube224_1.geometry} material={materials['Scratched Metal 2.011']} />
      </group>
      <mesh geometry={nodes.Cube107.geometry} material={materials['Cement.005']} position={[-0.066, -2.958, 7.123]} rotation={[0, -1.571, 0]} scale={0.846} />
      <mesh geometry={nodes.Cube108.geometry} material={materials['Cement.005']} position={[-5.625, -2.958, 7.666]} rotation={[0, -1.571, 0]} scale={0.846} />
      <group position={[-5.49, -2.958, 2.872]} rotation={[0, -1.571, 0]} scale={0.846}>
        <mesh geometry={nodes.Cube229.geometry} material={materials['Cement.005']} />
        <mesh geometry={nodes.Cube229_1.geometry} material={materials['Flat Wood 2.005']} />
        <mesh geometry={nodes.Cube229_2.geometry} material={materials['Scratched Metal 2.011']} />
        <mesh geometry={nodes.Cube229_3.geometry} material={materials.glass} />
      </group>
      <group position={[7.948, -2.958, 7.855]} scale={[0.846, 0.744, 0.846]}>
        <mesh geometry={nodes.Cube230.geometry} material={materials['Cement.005']} />
        <mesh geometry={nodes.Cube230_1.geometry} material={materials['Scratched Metal 2.011']} />
      </group>
      <group position={[-5.817, -2.958, -5.968]} rotation={[0, -1.571, 0]} scale={[0.846, 0.749, 0.846]}>
        <mesh geometry={nodes.Cube231.geometry} material={materials['Cement.005']} />
        <mesh geometry={nodes.Cube231_1.geometry} material={materials['Scratched Metal 2.011']} />
      </group>
      <mesh geometry={nodes.Cube112.geometry} material={materials['Metal Gloss.015']} position={[-6.927, -0.404, -0.536]} rotation={[0, -1.571, 0]} scale={[1.11, 0.846, 0.846]} />
      <mesh geometry={nodes.Cube123.geometry} material={materials['Bumped Metal.006']} position={[5.249, 3.968, 7.132]} rotation={[0, 0, -Math.PI / 2]} scale={[0.846, 1.328, 0.846]} />
      <mesh geometry={nodes.Cube124.geometry} material={materials['Bumped Metal.006']} position={[6.5, 2.842, 7.132]} scale={[0.846, 1.257, 0.846]} />
      <group position={[1.578, -0.074, 5.077]}>
        <mesh geometry={nodes.Cube065_1.geometry} material={materials.beige_wood} />
        <mesh geometry={nodes.Cube065_2.geometry} material={materials.salmon_wood} />
      </group>
      <group position={[-1.542, -0.074, 5.077]}>
        <mesh geometry={nodes.Cube065_1.geometry} material={materials.beige_wood} />
        <mesh geometry={nodes.Cube065_2.geometry} material={materials.salmon_wood} />
      </group>
      <mesh geometry={nodes.Cube127.geometry} material={materials['Bumped Metal.006']} position={[-5.088, 3.984, -5.801]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.846, 1.328, 0.846]} />
      <mesh geometry={nodes.Cube128.geometry} material={materials['Bumped Metal.006']} position={[-5.088, 2.858, -4.576]} rotation={[0, -1.571, 0]} scale={[0.846, 1.257, 0.846]} />
      <mesh geometry={nodes.Cube129.geometry} material={materials.black_metal} position={[6.242, 0.331, 4.736]} />
      <group position={[8.37, -0.014, 4.736]}>
        <mesh geometry={nodes.Cube070_1.geometry} material={materials.beige_wood} />
        <mesh geometry={nodes.Cube070_2.geometry} material={materials.salmon_wood} />
      </group>
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.006']} position={[8.077, 1.018, 1.209]} rotation={[0, -1.283, 0]} scale={[0.043, 0.095, 0.043]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.006']} position={[8.247, 1.018, 1.822]} rotation={[0, -1.283, 0]} scale={[0.043, 0.095, 0.043]} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials['Material.006']} position={[8.284, 1.018, 1.209]} rotation={[0, -0.771, 0]} scale={[0.043, 0.095, 0.043]} />
      <group position={[-0.157, -0.013, -3.321]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects012.geometry} material={materials.black_metal} />
        <mesh geometry={nodes.all_static_objects012_1.geometry} material={materials['glass.001']} />
      </group>
      <group position={[0.082, -0.018, 0.744]} scale={0.8}>
        <mesh geometry={nodes.elevator_interaction_v1_1.geometry} material={materials.elevatorMetal} />
        <mesh geometry={nodes.elevator_interaction_v1_2.geometry} material={materials.elevatorMetalDark} />
        <mesh geometry={nodes.elevator_interaction_v1_3.geometry} material={materials.dark_red} />
      </group>
      <mesh geometry={nodes.empireStrikesBack_interaction_v1.geometry} material={materials['empire strikes back']} position={[8.116, 5.47, 5.46]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes['fear&Loathing_interaction_v1'].geometry} material={materials['fear & loathing']} position={[7.045, 5.421, -6.081]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.fordVFerrari_interaction_v1.geometry} material={materials.fordVFerrari_interaction_v1} position={[1.668, 5.424, -6.083]} rotation={[Math.PI / 2, 0, 0]} scale={0.29} />
      <mesh geometry={nodes.gunShy_interaction_v1.geometry} material={materials.gunShy_interaction_v1} position={[3.453, 5.424, -6.083]} rotation={[Math.PI / 2, 0, 0]} scale={0.29} />
      <mesh geometry={nodes.interstellar_interaction_v1.geometry} material={materials.interstellar_interaction_v1} position={[5.268, 5.424, -6.083]} rotation={[Math.PI / 2, 0, 0]} scale={0.29} />
      <mesh geometry={nodes.kolya_interaction_v1.geometry} material={materials.kolya_interaction_v1} position={[8.099, 5.424, -4.898]} rotation={[1.572, 0, 1.573]} scale={0.29} />
      <mesh geometry={nodes.lebanon_interaction_v1.geometry} material={materials.lebanon_interaction_v1} position={[8.099, 5.424, -3.174]} rotation={[1.572, 0, 1.573]} scale={0.29} />
      <mesh geometry={nodes.likeWater4Chocolate_interaction_v1.geometry} material={materials.likeWater4Chocolate_interaction_v1} position={[8.099, 5.424, -1.448]} rotation={[1.572, 0, 1.573]} scale={0.29} />
      <group position={[-0.157, -0.013, -3.286]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects.geometry} material={materials['aiStandardSurface58w/Texture.001']} />
        <mesh geometry={nodes.all_static_objects_1.geometry} material={materials.beige_wood} />
        <mesh geometry={nodes.all_static_objects_2.geometry} material={materials.salmon_wood} />
        <mesh geometry={nodes.all_static_objects_3.geometry} material={materials.white_soft} />
        <mesh geometry={nodes.all_static_objects_4.geometry} material={materials.beige_wood_frame} />
        <mesh geometry={nodes.all_static_objects_5.geometry} material={materials.black_metal} />
        <mesh geometry={nodes.all_static_objects_6.geometry} material={materials.black_frame} />
        <mesh geometry={nodes.all_static_objects_7.geometry} material={materials.light_black_metal} />
        <mesh geometry={nodes.all_static_objects_8.geometry} material={materials.emissionLight} />
        <mesh geometry={nodes.all_static_objects_9.geometry} material={materials.elevatorRug} />
      </group>
      <group position={[-0.283, -0.013, -3.309]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects001.geometry} material={materials.gold_metal} />
        <mesh geometry={nodes.all_static_objects001_1.geometry} material={materials.lamp_shade_brown} />
        <mesh geometry={nodes.all_static_objects001_2.geometry} material={materials.lamp_shade_beige} />
        <mesh geometry={nodes.all_static_objects001_3.geometry} material={materials.dark_gold_metal} />
      </group>
      <group position={[3.662, 0.39, -0.401]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects049.geometry} material={materials.beige_wood} />
        <mesh geometry={nodes.all_static_objects049_1.geometry} material={materials.salmon_wood} />
      </group>
      <group position={[-0.157, -0.013, -3.286]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects003.geometry} material={materials.beige_wood} />
        <mesh geometry={nodes.all_static_objects003_1.geometry} material={materials.dark_red} />
      </group>
      <mesh geometry={nodes.lobby_all_static_objects004.geometry} material={materials.black_frame} position={[3.62, 5.181, 6.834]} scale={0.29} />
      <mesh geometry={nodes.lobby_all_static_objects005.geometry} material={materials.black_frame} position={[-4.745, 5.179, -1.813]} scale={0.29} />
      <mesh geometry={nodes.lobby_all_static_objects006.geometry} material={materials.black_frame} position={[-4.046, 2.01, 7.496]} scale={0.29} />
      <group position={[5.242, 0.39, -0.401]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects054.geometry} material={materials.beige_wood} />
        <mesh geometry={nodes.all_static_objects054_1.geometry} material={materials.salmon_wood} />
      </group>
      <mesh geometry={nodes.lobby_all_static_objects008.geometry} material={materials.black_frame} position={[-0.061, -0.013, -3.235]} scale={0.29} />
      <mesh geometry={nodes.lobby_all_static_objects009.geometry} material={materials.black_frame} position={[-0.226, 0.19, -3.297]} scale={0.29} />
      <group position={[-4.905, 5.179, 5.628]} rotation={[0, -Math.PI / 2, 0]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects021.geometry} material={materials.black_frame} />
        <mesh geometry={nodes.all_static_objects021_1.geometry} material={materials.dark_red} />
      </group>
      <group position={[-5.873, 5.514, 1.911]} rotation={[0, Math.PI / 2, 0]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects023.geometry} material={materials.black_frame} />
        <mesh geometry={nodes.all_static_objects023_1.geometry} material={materials.glass} />
        <mesh geometry={nodes.all_static_objects023_2.geometry} material={materials['Bumped Metal.006']} />
      </group>
      <mesh geometry={nodes.lobby_all_static_objects012.geometry} material={materials.black_frame} position={[-0.157, -0.013, -3.286]} scale={0.29} />
      <mesh geometry={nodes.lobby_all_static_objects013.geometry} material={materials.black_frame} position={[-5.448, 2.01, 5.916]} rotation={[0, Math.PI / 2, 0]} scale={0.29} />
      <mesh geometry={nodes.lobby_all_static_objects014.geometry} material={materials.black_frame} position={[-5.451, 1.887, 0.283]} scale={0.29} />
      <mesh geometry={nodes.lobby_all_static_objects015.geometry} material={materials.black_frame} position={[-5.451, 1.887, -2.985]} scale={0.29} />
      <group position={[-5.873, 8.679, 1.911]} rotation={[0, Math.PI / 2, 0]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects028.geometry} material={materials.black_frame} />
        <mesh geometry={nodes.all_static_objects028_1.geometry} material={materials.glass} />
        <mesh geometry={nodes.all_static_objects028_2.geometry} material={materials['Bumped Metal.006']} />
      </group>
      <group position={[-0.039, 8.679, 7.902]} rotation={[Math.PI, 0, Math.PI]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects030.geometry} material={materials.black_frame} />
        <mesh geometry={nodes.all_static_objects030_1.geometry} material={materials.glass} />
        <mesh geometry={nodes.all_static_objects030_2.geometry} material={materials['Bumped Metal.006']} />
      </group>
      <mesh geometry={nodes.lobby_all_static_objects020.geometry} material={materials.beige_wood} position={[-0.157, -0.005, -3.286]} />
      <group position={[-0.157, -0.013, -3.884]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects036.geometry} material={materials.sofaBlue} />
        <mesh geometry={nodes.all_static_objects036_1.geometry} material={materials.dark_red} />
      </group>
      <group position={[-0.157, -0.013, -3.884]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects038.geometry} material={materials.sofaBlue} />
        <mesh geometry={nodes.all_static_objects038_1.geometry} material={materials.dark_red} />
      </group>


      <group position={[-3.445, 0.231, -1.87]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects039.geometry} material={materials.table_glass} />
        <mesh geometry={nodes.all_static_objects039_1.geometry} material={materials.black_frame} />
      </group>

      
      <group position={[-0.157, -0.035, -3.884]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects040.geometry} material={materials.grey} />
        <mesh geometry={nodes.all_static_objects040_1.geometry} material={materials.magazine} />
        <mesh geometry={nodes.all_static_objects040_2.geometry} material={materials['magazine.002']} />
      </group>
      <group position={[-0.157, -0.013, -3.884]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects044.geometry} material={materials.white_soft} />
        <mesh geometry={nodes.all_static_objects044_1.geometry} material={materials.sofaBlue} />
        <mesh geometry={nodes.all_static_objects044_2.geometry} material={materials.dark_wood_texture} />
      </group>
      <group position={[-0.157, -0.013, -3.286]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects050.geometry} material={materials.gold_metal} />
        <mesh geometry={nodes.all_static_objects050_1.geometry} material={materials.lamp_shade_brown} />
        <mesh geometry={nodes.all_static_objects050_2.geometry} material={materials.lamp_shade_beige} />
        <mesh geometry={nodes.all_static_objects050_3.geometry} material={materials.dark_gold_metal} />
      </group>
      <group position={[-0.157, -0.013, -3.884]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects046.geometry} material={materials.gold_metal} />
        <mesh geometry={nodes.all_static_objects046_1.geometry} material={materials.green_metal} />
      </group>
      <mesh geometry={nodes.lobby_all_static_objects034.geometry} material={materials.white_soft} position={[-0.157, -0.013, -3.884]} scale={0.29} />
      <group position={[-0.157, -0.013, -3.879]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects048.geometry} material={materials.dark_green_stem} />
        <mesh geometry={nodes.all_static_objects048_1.geometry} material={materials.light_green_leaf} />
        <mesh geometry={nodes.all_static_objects048_2.geometry} material={materials.pink_leaf} />
        <mesh geometry={nodes.all_static_objects048_3.geometry} material={materials.orange_leaf} />
        <mesh geometry={nodes.all_static_objects048_4.geometry} material={materials.light_leaf} />
      </group>
      <group position={[-4.805, 0.309, 1.093]} rotation={[-Math.PI, 1.394, -Math.PI]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects072.geometry} material={materials.white_soft} />
        <mesh geometry={nodes.all_static_objects072_1.geometry} material={materials.sofaBlue} />
        <mesh geometry={nodes.all_static_objects072_2.geometry} material={materials.dark_wood_texture} />
      </group>
      <group position={[-0.157, -0.013, -3.884]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects051.geometry} material={materials.dark_wood_texture} />
        <mesh geometry={nodes.all_static_objects051_1.geometry} material={materials.table_glass} />
      </group>
      <group position={[-0.157, -0.013, -3.884]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects052.geometry} material={materials.grey} />
        <mesh geometry={nodes.all_static_objects052_1.geometry} material={materials['magazine.001']} />
      </group>
      <group position={[4.774, 0.488, 6.104]} rotation={[0, Math.PI / 2, 0]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects053.geometry} material={materials.beige_wood} />
        <mesh geometry={nodes.all_static_objects053_1.geometry} material={materials.dark_wood_texture} />
      </group>
      <group position={[-0.157, -0.013, 3.445]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects070.geometry} material={materials.sofaBlue} />
        <mesh geometry={nodes.all_static_objects070_1.geometry} material={materials.dark_red} />
      </group>
      <group position={[6.575, 0.246, 6.348]} rotation={[-Math.PI, 1.332, -Math.PI]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects056.geometry} material={materials.white_soft} />
        <mesh geometry={nodes.all_static_objects056_1.geometry} material={materials.black_metal} />
      </group>
      <group position={[4.798, 0.843, 6.345]} rotation={[0, 1.57, 0]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects057.geometry} material={materials.black_metal} />
        <mesh geometry={nodes.all_static_objects057_1.geometry} material={materials.black_frame} />
        <mesh geometry={nodes.all_static_objects057_2.geometry} material={materials.white} />
      </group>
      <group position={[4.793, 0.396, -6.517]} rotation={[Math.PI, 0, Math.PI]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects020.geometry} material={materials.sofaBlue} />
        <mesh geometry={nodes.all_static_objects020_1.geometry} material={materials.dark_red} />
      </group>
      <group position={[4.725, 0.224, -4.941]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects024.geometry} material={materials.dark_wood_texture} />
        <mesh geometry={nodes.all_static_objects024_1.geometry} material={materials.table_glass} />
      </group>
      <group position={[3.585, 0.309, -3.886]} rotation={[Math.PI, -0.239, Math.PI]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects029.geometry} material={materials.white_soft} />
        <mesh geometry={nodes.all_static_objects029_1.geometry} material={materials.sofaBlue} />
        <mesh geometry={nodes.all_static_objects029_2.geometry} material={materials.dark_wood_texture} />
      </group>


      <group position={[-4.623, 1.234, -5.839]} rotation={[Math.PI, -0.762, Math.PI]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects063.geometry} material={materials.black_metal} />
        <mesh geometry={nodes.all_static_objects063_1.geometry} material={materials.grey_camera} />
      </group>


      <group position={[-0.157, -0.013, -3.286]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects064.geometry} material={materials.lamp_shade_brown} />
        <mesh geometry={nodes.all_static_objects064_1.geometry} material={materials.lamp_shade_beige} />
      </group>
      <group position={[-3.395, 0.309, 3.67]} rotation={[0, 0.748, 0]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects013.geometry} material={materials.white_soft} />
        <mesh geometry={nodes.all_static_objects013_1.geometry} material={materials.sofaBlue} />
        <mesh geometry={nodes.all_static_objects013_2.geometry} material={materials.dark_wood_texture} />
      </group>
      <group position={[-4.907, 0.309, 5.295]} rotation={[-Math.PI, 0.86, -Math.PI]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects043.geometry} material={materials.white_soft} />
        <mesh geometry={nodes.all_static_objects043_1.geometry} material={materials.sofaBlue} />
        <mesh geometry={nodes.all_static_objects043_2.geometry} material={materials.dark_wood_texture} />
      </group>
      <mesh geometry={nodes.lobby_all_static_objects051.geometry} material={materials.black_frame} position={[6.461, 5.181, 6.834]} scale={0.29} />
      <group position={[-4.87, 0.953, 4.307]} rotation={[0, -1.337, 0]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects068.geometry} material={materials.black_frame} />
        <mesh geometry={nodes.all_static_objects068_1.geometry} material={materials['chandelier-emission']} />
      </group>
      <group position={[-4.687, 0.953, -4.978]} rotation={[Math.PI, -0.521, Math.PI]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects069.geometry} material={materials.black_frame} />
        <mesh geometry={nodes.all_static_objects069_1.geometry} material={materials['chandelier-emission']} />
      </group>
      <mesh geometry={nodes.lobby_all_static_objects054.geometry} material={materials.beige_wood_frame} position={[-0.157, -0.013, -3.286]} scale={0.29} />
      <group position={[-3.396, 0.231, 5.145]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects073.geometry} material={materials.table_glass} />
        <mesh geometry={nodes.all_static_objects073_1.geometry} material={materials.black_frame} />
      </group>
      <group position={[-1.521, -0.013, -3.204]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects075.geometry} material={materials.beige_wood_frame} />
        <mesh geometry={nodes.all_static_objects075_1.geometry} material={materials.marble_texture} />
      </group>
      <mesh geometry={nodes.lobby_all_static_objects058.geometry} material={materials.beige_wood_frame} position={[-0.157, -0.013, -3.308]} scale={0.29} />
      <mesh geometry={nodes.lobby_all_static_objects059.geometry} material={materials.black_frame} position={[-4.745, 5.179, -4.56]} scale={0.29} />
      <group position={[7.838, 0.595, 6.801]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects079.geometry} material={materials.green_metal} />
        <mesh geometry={nodes.all_static_objects079_1.geometry} material={materials.brown_soil} />
        <mesh geometry={nodes.all_static_objects079_2.geometry} material={materials.dark_green_stem} />
        <mesh geometry={nodes.all_static_objects079_3.geometry} material={materials.light_green_leaf} />
      </group>
      <group position={[4.453, 3.295, -3.624]} rotation={[0, Math.PI / 2, 0]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects037.geometry} material={materials['beige_wood.002']} />
        <mesh geometry={nodes.all_static_objects037_1.geometry} material={materials['salmon_wood.002']} />
      </group>
      <group position={[8.34, -0.013, -3.204]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects041.geometry} material={materials.beige_wood_frame} />
        <mesh geometry={nodes.all_static_objects041_1.geometry} material={materials.marble_texture} />
      </group>
      <mesh geometry={nodes.lobby_all_static_objects063.geometry} material={materials.dark_wood_texture} position={[4.773, 0.488, 5.982]} rotation={[0, Math.PI / 2, 0]} scale={0.29} />
      <group position={[-0.157, -0.013, -3.286]} scale={0.29}>
        <mesh geometry={nodes.walkable_paths.geometry} material={materials['lobby-floor']} />
        <mesh geometry={nodes.walkable_paths_1.geometry} material={materials.beige_floor} />
      </group>
      <mesh geometry={nodes.lobby_walkable_paths001.geometry} material={materials['beige_floor.001']} position={[4.488, 2.606, -3.584]} rotation={[0, Math.PI / 2, 0]} scale={0.29} />
      <mesh geometry={nodes.lobby_walkable_paths002.geometry} material={materials['aiStandardSurface58w/Texture.001']} position={[-0.157, -0.013, -3.286]} scale={0.29} />
      <mesh geometry={nodes.madMaxFuryRoad_interaction_v1.geometry} material={materials.madMaxFuryRoad_interaction_v1} position={[8.099, 5.424, 0.27]} rotation={[1.572, 0, 1.573]} scale={0.29} />
      <mesh geometry={nodes.manOnFire_interaction_v1.geometry} material={materials.manOnFire_interaction_v1} position={[8.098, 5.432, 1.995]} rotation={[1.572, 0, 1.573]} scale={0.29} />
      <group position={[1.507, 3.594, 0.541]} rotation={[0, -1.571, 0]} scale={0.846}>
        <mesh geometry={nodes.Cube135.geometry} material={materials['Cement.005']} />
        <mesh geometry={nodes.Cube135_1.geometry} material={materials['Scratched Metal 2.011']} />
      </group>
      <mesh geometry={nodes.middle_layer001.geometry} material={materials['Scratched Metal 2.010']} position={[5.463, 2.861, 7.815]} rotation={[0, -1.571, 0]} scale={[0.846, 0.846, 0.694]} />
      <group position={[1.507, 2.858, 0.541]} rotation={[0, -1.571, 0]} scale={0.846}>
        <mesh geometry={nodes.Cube134.geometry} material={materials['Cement.005']} />
        <mesh geometry={nodes.Cube134_1.geometry} material={materials['Scratched Metal 2.010']} />
        <mesh geometry={nodes.Cube134_2.geometry} material={materials['Scratched Metal 2.011']} />
        <mesh geometry={nodes.Cube134_3.geometry} material={materials['Glide.010']} />
        <mesh geometry={nodes.Cube134_4.geometry} material={materials['Bumped Metal.006']} />
      </group>
      <mesh geometry={nodes.middle_layer004.geometry} material={materials['Scratched Metal 2.010']} position={[3.153, 2.861, 7.815]} rotation={[0, -1.571, 0]} scale={[0.846, 0.846, 0.694]} />
      <mesh geometry={nodes.middle_layer005.geometry} material={materials['Scratched Metal 2.010']} position={[-3.755, 2.864, 7.815]} rotation={[Math.PI, -1.571, 0]} scale={[-0.846, -0.846, -1.043]} />
      <mesh geometry={nodes.middle_layer006.geometry} material={materials['Scratched Metal 2.010']} position={[-5.739, 2.852, 5.776]} rotation={[-Math.PI, 0, 0]} scale={[-0.846, -0.846, -1.166]} />
      <mesh geometry={nodes.middle_layer007.geometry} material={materials['Scratched Metal 2.010']} position={[-5.739, 2.852, 0.264]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.middle_layer008.geometry} material={materials['Scratched Metal 2.010']} position={[-5.739, 2.852, -2.991]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes['mr&MrsSmith_interaction_v1'].geometry} material={materials['mr&MrsSmith_interaction_v1']} position={[8.099, 5.424, 3.734]} rotation={[1.572, 0, 1.573]} scale={0.29} />
      <mesh geometry={nodes.Plane010.geometry} material={materials.script} position={[-5.139, 0.434, 3.256]} rotation={[0, 1.571, 0]} scale={0.961} />
      <mesh geometry={nodes.Plane013.geometry} material={materials.script} position={[-5.128, 0.446, 3.027]} rotation={[-2.998, 1.556, 2.915]} />
      <mesh geometry={nodes.Plane016.geometry} material={materials.glass} position={[-5.581, 1.62, 5.72]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Plane018.geometry} material={materials.glass} position={[-5.581, 1.62, 0.213]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Plane019.geometry} material={materials.glass} position={[2.26, 7.558, 7.134]} rotation={[Math.PI / 2, 0, 0]} scale={[0.393, 0.846, 0.846]} />
      <mesh geometry={nodes.Plane020.geometry} material={materials.glass} position={[-5.581, 1.62, -3.062]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Plane021.geometry} material={materials.glass} position={[-3.822, 1.62, 7.599]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Plane022.geometry} material={materials.glass} position={[-5.164, 7.575, 7.134]} rotation={[Math.PI / 2, 0, 0]} scale={[0.209, 0.846, 0.846]} />
      <mesh geometry={nodes.Plane023.geometry} material={materials.glass} position={[3.206, 1.62, 7.605]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Plane024.geometry} material={materials.glass} position={[-5.062, 7.514, -5.849]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.379, 0.846, 0.862]} />
      <mesh geometry={nodes.Plane025.geometry} material={materials.glass} position={[-5.062, 7.534, 4.191]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.209, 0.846, 0.846]} />
      <mesh geometry={nodes.Plane026.geometry} material={materials.glass} position={[5.572, 1.62, 7.606]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Plane027.geometry} material={materials.glass} position={[-5.457, -1.863, 4.017]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.225, 0.846, 0.846]} />
      <mesh geometry={nodes.Plane028.geometry} material={materials.glass} position={[-5.53, -1.863, 7.569]} rotation={[Math.PI / 2, 0, 0]} scale={0.846} />
      <mesh geometry={nodes.Plane029.geometry} material={materials.glass} position={[6.448, 5.163, 7.132]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Plane030.geometry} material={materials.glass} position={[3.614, 5.163, 7.132]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Plane031.geometry} material={materials.glass} position={[-3.625, 5.163, 7.132]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Plane032.geometry} material={materials.glass} position={[-5.068, 5.163, 5.65]} rotation={[Math.PI, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Plane033.geometry} material={materials.glass} position={[-5.068, 5.163, -1.759]} rotation={[Math.PI, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Plane034.geometry} material={materials.glass} position={[-5.068, 5.163, -4.493]} rotation={[Math.PI, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Plane036.geometry} material={materials.glass} position={[-0.008, 5.454, 7.956]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Plane037.geometry} material={materials['Cement.005']} position={[-0.026, -3.736, 10.941]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane045.geometry} material={materials.script} position={[-5.191, 0.806, 2.767]} rotation={[-2.474, 1.549, 2.466]} scale={0.961} />
      <mesh geometry={nodes.Plane046.geometry} material={materials.script} position={[-5.179, 0.82, 2.996]} rotation={[0.114, 1.476, -0.059]} />
      <mesh geometry={nodes.Plane047.geometry} material={materials.script} position={[-5.193, 1.183, 3.292]} rotation={[0.084, 1.453, -0.082]} scale={0.961} />
      <mesh geometry={nodes.Plane048.geometry} material={materials.script} position={[-5.206, 1.195, 3.053]} rotation={[2.208, 1.533, -2.283]} scale={0.961} />
      <mesh geometry={nodes.Plane049.geometry} material={materials.script} position={[-3.62, 0.335, 5.173]} rotation={[0.084, 1.453, -0.082]} scale={0.961} />
      <mesh geometry={nodes.Plane050.geometry} material={materials.script} position={[-3.309, 0.349, 5.044]} rotation={[2.208, 1.533, -2.283]} scale={0.961} />
      <mesh geometry={nodes.Plane051.geometry} material={materials.script} position={[-3.428, 0.475, 1.93]} rotation={[0.356, 1.432, -0.339]} scale={0.961} />
      <mesh geometry={nodes.Plane069.geometry} material={materials.script} position={[-5.26, 1.565, 2.732]} rotation={[2.35, 1.534, -2.35]} scale={0.961} />
      <mesh geometry={nodes.Plane070.geometry} material={materials.script} position={[-5.255, 1.584, 2.893]} rotation={[2.29, 1.523, -2.14]} scale={0.961} />
      <mesh geometry={nodes.planetOfTheApes_interaction_v1.geometry} material={materials['planet of the apes']} position={[6.66, 1.867, -7.002]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-0.157, -0.013, -3.286]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects004.geometry} material={materials.green_metal} />
        <mesh geometry={nodes.all_static_objects004_1.geometry} material={materials.brown_soil} />
        <mesh geometry={nodes.all_static_objects004_2.geometry} material={materials.dark_green_stem} />
        <mesh geometry={nodes.all_static_objects004_3.geometry} material={materials.light_green_leaf} />
      </group>
      <group position={[-5.105, 0.777, 6.917]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects006.geometry} material={materials.green_metal} />
        <mesh geometry={nodes.all_static_objects006_1.geometry} material={materials.brown_soil} />
        <mesh geometry={nodes.all_static_objects006_2.geometry} material={materials.dark_green_stem} />
        <mesh geometry={nodes.all_static_objects006_3.geometry} material={materials.light_green_leaf} />
      </group>
      <group position={[-0.157, -0.013, -3.286]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects007.geometry} material={materials.green_metal} />
        <mesh geometry={nodes.all_static_objects007_1.geometry} material={materials.brown_soil} />
        <mesh geometry={nodes.all_static_objects007_2.geometry} material={materials.dark_green_stem} />
        <mesh geometry={nodes.all_static_objects007_3.geometry} material={materials.light_green_leaf} />
      </group>
      <group position={[-0.157, -0.013, -3.286]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects008.geometry} material={materials.green_metal} />
        <mesh geometry={nodes.all_static_objects008_1.geometry} material={materials.brown_soil} />
        <mesh geometry={nodes.all_static_objects008_2.geometry} material={materials.dark_green_stem} />
        <mesh geometry={nodes.all_static_objects008_3.geometry} material={materials.light_green_leaf} />
      </group>
      <group position={[5.481, 4.153, -4.88]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects010.geometry} material={materials.green_metal} />
        <mesh geometry={nodes.all_static_objects010_1.geometry} material={materials.brown_soil} />
        <mesh geometry={nodes.all_static_objects010_2.geometry} material={materials.dark_green_stem} />
        <mesh geometry={nodes.all_static_objects010_3.geometry} material={materials.light_green_leaf} />
      </group>
      <group position={[-3.661, -0.013, -5.544]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects009.geometry} material={materials.green_metal} />
        <mesh geometry={nodes.all_static_objects009_1.geometry} material={materials.brown_soil} />
        <mesh geometry={nodes.all_static_objects009_2.geometry} material={materials.dark_green_stem} />
        <mesh geometry={nodes.all_static_objects009_3.geometry} material={materials.light_green_leaf} />
      </group>
      <group position={[-0.157, -0.013, -3.286]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects011.geometry} material={materials.green_metal} />
        <mesh geometry={nodes.all_static_objects011_1.geometry} material={materials.brown_soil} />
        <mesh geometry={nodes.all_static_objects011_2.geometry} material={materials.dark_green_stem} />
        <mesh geometry={nodes.all_static_objects011_3.geometry} material={materials.light_green_leaf} />
      </group>
      <group position={[-0.157, -0.013, -3.286]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects005.geometry} material={materials.green_metal} />
        <mesh geometry={nodes.all_static_objects005_1.geometry} material={materials.brown_soil} />
        <mesh geometry={nodes.all_static_objects005_2.geometry} material={materials.dark_green_stem} />
        <mesh geometry={nodes.all_static_objects005_3.geometry} material={materials.light_green_leaf} />
      </group>
      <group position={[-2.555, 0.584, -6.678]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects042.geometry} material={materials.green_metal} />
        <mesh geometry={nodes.all_static_objects042_1.geometry} material={materials.brown_soil} />
        <mesh geometry={nodes.all_static_objects042_2.geometry} material={materials.dark_green_stem} />
        <mesh geometry={nodes.all_static_objects042_3.geometry} material={materials.light_green_leaf} />
      </group>
      <group position={[2.553, 0.595, -6.464]} scale={0.29}>
        <mesh geometry={nodes.all_static_objects045.geometry} material={materials.green_metal} />
        <mesh geometry={nodes.all_static_objects045_1.geometry} material={materials.brown_soil} />
        <mesh geometry={nodes.all_static_objects045_2.geometry} material={materials.dark_green_stem} />
        <mesh geometry={nodes.all_static_objects045_3.geometry} material={materials.light_green_leaf} />
      </group>
      <mesh geometry={nodes.scriptBoard_interaction_v1.geometry} material={materials.scriptBoard_interaction_v1} position={[0.059, 1.738, -6.874]} rotation={[Math.PI / 2, 0, 0]} scale={0.29} />
      <mesh geometry={nodes.Simple_GP_Layer.geometry} material={materials.black_metal} position={[-27.685, -3.876, -22.236]} />
      <group position={[-0.304, 2.917, 8.683]} rotation={[Math.PI, 0, -0.136]} scale={0.616}>
        <mesh geometry={nodes.TCom_ArtDecoSet01_01006.geometry} material={materials['Scratched Metal 2.011']} />
        <mesh geometry={nodes.TCom_ArtDecoSet01_01006_1.geometry} material={materials['Cement.005']} />
      </group>
      <mesh geometry={nodes.the_big_lebowski_interaction_v1.geometry} material={materials['the big lebowski']} position={[-2.858, 1.856, -7.012]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.theGodfather_interaction_v1.geometry} material={materials.theGodfather_interaction_v1} position={[8.56, 1.997, -4.843]} rotation={[1.572, 0, 1.573]} scale={0.29} />
      <mesh geometry={nodes.theShining_interaction_v1.geometry} material={materials.theShining_interaction_v1} position={[8.56, 1.997, -2.802]} rotation={[1.572, 0, 1.573]} scale={0.29} />
      <mesh geometry={nodes.Us_interaction_v1.geometry} material={materials['Us movei poster']} position={[3.067, 1.857, -7.01]} rotation={[Math.PI / 2, 0, 0]} />
      
      <mesh geometry={nodes.Wolf3D_Body001.geometry} material={materials.Wolf3D_Body} position={[5.769, -0.013, 5.995]} rotation={[Math.PI / 2, 0, 1.392]} scale={0.01} />
      <mesh geometry={nodes.Wolf3D_Glasses001.geometry} material={materials.Wolf3D_Glasses} position={[5.769, -0.013, 5.995]} rotation={[Math.PI / 2, 0, 1.392]} scale={0.01} />
      <mesh geometry={nodes.Wolf3D_Hair001.geometry} material={materials.Wolf3D_Hair} position={[5.769, -0.013, 5.995]} rotation={[Math.PI / 2, 0, 1.392]} scale={0.01} />
      <mesh geometry={nodes.Wolf3D_Outfit_Bottom001.geometry} material={materials['Wolf3D_Outfit_Bottom.002']} position={[5.769, -0.013, 5.995]} rotation={[Math.PI / 2, 0, 1.392]} scale={0.01} />
      <mesh geometry={nodes.Wolf3D_Outfit_Footwear001.geometry} material={materials.Wolf3D_Outfit_Footwear} position={[5.769, -0.013, 5.995]} rotation={[Math.PI / 2, 0, 1.392]} scale={0.01} />
      <mesh geometry={nodes.Wolf3D_Outfit_Top001.geometry} material={materials['Wolf3D_Outfit_Top.001']} position={[5.769, -0.013, 5.995]} rotation={[Math.PI / 2, 0, 1.392]} scale={0.01} />
      <mesh geometry={nodes.EyeLeft002.geometry} material={materials.Wolf3D_Eye} position={[5.769, -0.013, 5.995]} rotation={[Math.PI / 2, 0, 1.392]} scale={0.01} />
      <mesh geometry={nodes.EyeRight002.geometry} material={materials.Wolf3D_Eye} position={[5.769, -0.013, 5.995]} rotation={[Math.PI / 2, 0, 1.392]} scale={0.01} />
      <mesh geometry={nodes.Wolf3D_Head001.geometry} material={materials.Wolf3D_Skin} position={[5.769, -0.013, 5.995]} rotation={[Math.PI / 2, 0, 1.392]} scale={0.01} />
      <mesh geometry={nodes.Wolf3D_Teeth001.geometry} material={materials.Wolf3D_Teeth} position={[5.769, -0.013, 5.995]} rotation={[Math.PI / 2, 0, 1.392]} scale={0.01} />

    </group>
  )
}

useGLTF.preload('/assets/3d/scene.glb')
